"""esquema inicial: sensors y readings

Revision ID: 07dbb5e6d09b
Revises: 
Create Date: 2026-07-31 08:43:24.295912

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '07dbb5e6d09b'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
